name: github-page CD

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and deploy gh-pages
    env:
      PENNY_SECRET_TOKEN: ${{secrets.PENNY_SECRET_TOKEN}}
      USER_NAME: ${{secrets.USER_NAME}}
      USER_EMAIL: ${{secrets.USER_EMAIL}}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'
          registry-url: 'https://registry.npmjs.org'

      - name: Set up Git
        run: |
          git config --global user.email ${{secrets.USER_EMAIL}}
          git config --global user.name ${{secrets.USER_NAME}}
          git remote remove origin
          git remote add origin https://${{secrets.USER_NAME}}:${{secrets.PENNY_SECRET_TOKEN}}@github.com/${{secrets.USER_NAME}}/cicdTest.git

      - name: deploy
        run: |
          cd clientApp
          npm install
          npm run build
          npm run deploy